// Generated by https://quicktype.io

export interface TeamResponse {
  data: Team[];
}

export interface Team {
  id:           number;
  conference:   string;
  division:     string;
  city:         string;
  name:         string;
  full_name:    string;
  abbreviation: string;
}
